config/routes.rb
HelloWorld::Application.routes.draw do

  devise_for :users, :path => "auth",:controllers =>{passwords: "passwords", registrations: 'registrations'}
  resources :settings do
    post "normal_upload", :on => :collection
  end

  resources :banners do
  end
  
  resources :advertisings do
  end
  
  resources :categories
  resources :orders
  resources :organizations do
    resources :users

    resources :user_groups do
      get "get_available_user"
      get "add_user_to_group"
      get "update_permissions"
    end

    resources :activities
  end
  resources :calendars do
    get "contact",:on => :collection
    post "send_contact",:on => :collection
    get "product_contact"
    get "send_product_contact",:on =>:collection
    get "admin",:on =>:collection
  end
  root :to => 'home#index'
  resources :home do
    get "introduction",:on => :collection
    get "pricing_page",:on => :collection
  end

end

app/models/advertising.rb
# coding: UTF-8
require 'uri'
class Advertising < ActiveRecord::Base
  
  attr_accessible  :image,:link,:order_no,:is_deleted
  has_attached_file :image,
    :styles => {:large =>"800x360", :medium => "300x300>", :thumb => "100x100#",
    :default_url => '/assets/img_lich/lich_bloc.jpg' }
  validates_attachment_content_type :image, :content_type => /image/
  validates_format_of :link, :with => URI::regexp(%w(http https)),:message =>" không hợp lệ."
end

app/controllers/advertisings_controller.rb
class AdvertisingsController < ApplicationController
  before_filter :authenticate_user!
  layout "admin"
  
  def new
    @advertising = Advertising.new  
  end
  
  def edit
     @advertising = Advertising.find(params[:id])
  end
  
  def create
    @advertising = Advertising.new(params[:advertising])
    if @advertising.save
      redirect_to advertisings_path
    else
      render :new
    end
  end

  def index
    if request.xhr?
      per_page = params[:iDisplayLength] ||  10
      page = params[:iDisplayStart] ? ((params[:iDisplayStart].to_i/per_page.to_i) + 1) : 1
      search_text = params["sSearch"] || ""
      cols = ["link","image"]
      
      sort_field =  cols[(params[:iSortCol_0].to_i)] + " " + params[:sSortDir_0].to_s
      @ads = Advertising.order(sort_field).paginate(:per_page => per_page,:page =>page)
      @ads.each do |i|
        i["image_url"] = i.image.url(:thumb)
      end
      render :json => {"aaData" => @ads,"iTotalRecords"=>@ads.length,"iTotalDisplayRecords"=>@ads.length}
    end
  end
  
  def update
    @advertising = Advertising.find(params[:id])
    if @advertising.update_attributes(params[:advertising])
      redirect_to advertisings_path
    else
      render :edit
    end
  end

  def destroy
    if request.xhr?
      cate = Advertising.find(params[:id])
      render :json =>{"status" => "failed"} if cate.blank?
      cate.destroy
      render :json =>{"status" => "ok"}
    end
  end
end

app/views/advertisings/_form.html.haml
- if params[:success]
  %div{:style =>"color:green"}
    Quảng cáo đã được cập nhật thành công.
- url = @advertising.new_record? ? advertisings_path : advertising_path
= form_for @advertising, :url => url, :html => { :multipart => true } do |form|
  - if @advertising.errors.any?
    .alert.alert-error
      %div.head-error Có lỗi xảy ra. Vui lòng sửa các lỗi sau:
      %div.content-error
        %ul{:style => "list-style:none; padding:10px 10px 10px 10px;"}
          - for message in @advertising.errors.full_messages
            %li.li-error= message
  .row
    .col.col-lg-4
      Link:
    .col.col-lg-8
      =form.text_field :link
  .row
    .col.col-lg-4
      Hình ảnh:
    .col.col-lg-8
      -unless @advertising.new_record?
        = form.object.image.url(:thumb)
        = image_tag(form.object.image.url(:thumb)) 
      = form.file_field :image
  %br
  =form.submit "Lưu",:class=>"art-button"

app/views/advertisings/edit.html.haml
%h1{:style =>"color: black"}
  Sửa thông tin quảng cáo
%hr{:size => 1,:style =>"color: lightgray;margin: 1px 0px"}
%div
  =render :partial => "form"

app/views/advertisings/index.html.haml
=javascript_include_tag "advertising"
%h1{:style =>"color: black"}
  Danh sách quảng cáo
%hr{:size => 1,:style =>"color: lightgray;margin: 1px 0px"}
%div
  %a.btn.btn-primary{:href=>"#{new_advertising_path}"}
    Thêm mới

%div
%table{:cellpadding=>"0",:cellspacing=>"0",:class=>"table table-striped dataTable group-service-dataTable custom_datatable",:style=>"width:100%",:id =>"ads_list"}

app/views/advertisings/new.html.haml
%h1{:style =>"color: black"}
  Thêm mới quảng cáo
%hr{:size => 1,:style =>"color: lightgray;margin: 1px 0px"}
%div
  =render :partial => "form"