config/routes.rb
HelloWorld::Application.routes.draw do

  devise_for :users, :path => "auth",:controllers =>{passwords: "passwords", registrations: 'registrations'}
  resources :settings do
    post "normal_upload", :on => :collection
  end

  resources :banners do
  end
  
  resources :advertisings do
  end
  
  resources :categories
  resources :orders
  resources :organizations do
    resources :users

    resources :user_groups do
      get "get_available_user"
      get "add_user_to_group"
      get "update_permissions"
    end

    resources :activities
  end
  resources :calendars do
    get "contact",:on => :collection
    post "send_contact",:on => :collection
    get "product_contact"
    get "send_product_contact",:on =>:collection
    get "admin",:on =>:collection
  end
  root :to => 'home#index'
  resources :home do
    get "introduction",:on => :collection
    get "pricing_page",:on => :collection
  end

end

app/models/user_group.rb
# This model is used to comunicate with table UserGroup in database
# History: June 06, 2013
# By NamTV

class UserGroup < ActiveRecord::Base

  # Use to log actions
  include PublicActivity::Common
  after_update :after_update_group
  after_create :after_create_group
  before_destroy :before_destroy_group

  attr_accessible :name, :description, :is_active, :permissions, :organization, :organization_id, :users
  has_many :user_groups_users, :dependent => :destroy
  has_many :users, :through => :user_groups_users
  has_many :user_groups_permissions, :dependent => :destroy
  has_many :permissions, :through => :user_groups_permissions

  # Relationship with organization
  belongs_to :organization

  validates :name, :uniqueness => {:scope => :organization_id}

  scope :in_organization, lambda { |id| where(organization_id: id) }
  scope :search_name, lambda { |search| where("lower(name) like ?", "%" + search + "%") }
  scope :name_not, lambda { |except_name| where("name != ?", except_name) }

  ##
  #Get filtering searching user_group list except Administrator
  #Parameters::
  # * (Integer) *page*: page number that is needed to load
  # * (Integer) *per_page*: number of rows per page
  # * (String) *search*: search string
  # * (String) *sort*: name of sorted column
  #Return::
  # * (Hash) Matched user list with paging and number all rows are finded
  #*Author*:: NamTV
  def self.get_all_user_groups(page, per_page, search, sort = nil,organization_id)
    sort ||= "name"
    search = search.downcase

    user_groups = self.name_not("Administrator").in_organization(organization_id)
    user_groups = user_groups.search_name(search) if !search.blank?
    return_data = {
      "aaData" => [],
      "iTotalDisplayRecords" => user_groups.count
    }
    user_groups = user_groups.order(sort).paginate(:page => page, :per_page => per_page)
    no = 1
    user_groups.each do |group|
      return_data["aaData"] << [
        no,
        group.name,
        group.description,
        group.is_active,
        "",
        group.id
      ]
      no += 1
    end
    return return_data
  end

  def self.get_all_users_in_group(page, per_page, search, sort = nil,organization_id, group_id)
    sort ||= "full_name"
    search = search.downcase
    user_group = self.name_not("Administrator").in_organization(organization_id).find(group_id)
    users = user_group.users
    users = users.where(:is_admin => false).select("users.id, concat(first_name, ' ', last_name) as full_name, username, is_deleted")

    users = users.where("lower(concat(first_name, ' ', last_name)) like ?", "%" + search + "%") if !search.blank?

    return_data = {
      "aaData" => [],
      "iTotalDisplayRecords" => users.count
    }
    users = users.order(sort).paginate(:page => page, :per_page => per_page)
    no = per_page.to_i * (page.to_i-1) + 1
    users.each do |user|
      return_data["aaData"] << [
        no,
        user.full_name,
        user.username,
        user.is_deleted,
        "",
        user.id
      ]
      no += 1
    end
    return return_data
  end

  def self.get_all_users_not_in_group(page, per_page, search, sort = nil,organization_id, group_id)
    sort ||= "full_name"
    search = search.downcase
    user_group = self.name_not("Administrator").in_organization(organization_id).find(group_id)
    userids = user_group.user_ids
    except_users = userids.blank? ? User : User.not_in_user_group(userids)
    except_users = except_users.where(:is_admin => false).select("users.id, concat(first_name, ' ', last_name) as full_name, username, is_deleted")

    except_users = except_users.where("lower(concat(first_name, ' ', last_name)) like ?", "%" + search + "%") if !search.blank?

    return_data = {
      "aaData" => [],
      "iTotalDisplayRecords" => except_users.count
    }
    except_users = except_users.order(sort).paginate(:page => page, :per_page => per_page)
    no = per_page.to_i * (page.to_i-1) + 1
    except_users.each do |user|
      return_data["aaData"] << [
        no,
        user.full_name,
        user.username,
        user.is_deleted,
        "",
        user.id
      ]
      no += 1
    end
    return return_data
  end

  def self.get_all_users_in_org(page, per_page, search, sort = nil,organization_id)
    sort ||= "full_name"
    search = search.downcase
    users = User.where(:is_admin => false, :organization_id => organization_id).select("users.id, concat(first_name, ' ', last_name) as full_name, username, is_deleted")

    users = users.where("lower(concat(first_name, ' ', last_name)) like ?", "%" + search + "%") if !search.blank?

    return_data = {
      "aaData" => [],
      "iTotalDisplayRecords" => users.count
    }
    users = users.order(sort).paginate(:page => page, :per_page => per_page)
    no = per_page.to_i * (page.to_i-1) + 1
    users.each do |user|
      return_data["aaData"] << [
        no,
        user.full_name,
        user.username,
        user.is_deleted,
        "",
        user.id
      ]
      no += 1
    end
    return return_data
  end

  def get_hash_selected_permissions
    selected_permissions = {}
    self.permissions.each  do |p|
      if !selected_permissions[p.group_permission_name]
        selected_permissions[p.group_permission_name] = Permission.select("id, name").where(:id => p.id)
      else
        selected_permissions[p.group_permission_name] += Permission.select("id, name").where(:id => p.id)
      end
    end
    return selected_permissions
  end

  ##
  #Get group list in a organization
  #Parameters::
  # *(Integer) *organization_id*: id of organization
  #Return::
  # * Matched group list
  #*Author*:: PhuND
  def self.get_all_user_groups_in_org(organization_id)
    user_groups = self.in_organization(organization_id)
  end

  protected
  ##
  # Write logs after update group
  #*Author*:: NamTV
  def after_update_group

    controller = PublicActivity.get_controller

    # Return if seeding or nothing changes
    return if !controller || self.changed.blank?

    current_user = PublicActivity.get_controller.current_user

    self.create_activity :update, owner: current_user,organization_id: self.organization_id, params: {:detail => I18n.t('logs.update_group', group_name: self.name)}

  end

  ##
  # Write logs after create group
  #*Author*:: NamTV
  def after_create_group
    controller = PublicActivity.get_controller

    # Return if seeding or nothing changes
    return if !controller || self.changed.blank?

    current_user = PublicActivity.get_controller.current_user

    self.create_activity :create, owner: current_user,organization_id: self.organization_id, params: {:detail => I18n.t('logs.create_group', group_name: self.name)}
  end

  ##
  # Write logs before remove group
  #*Author*:: NamTV
  def before_destroy_group
    controller = PublicActivity.get_controller

    # Return if seeding or nothing changes
    return if !controller

    current_user = PublicActivity.get_controller.current_user

    self.create_activity :destroy, owner: current_user,organization_id: self.organization_id, params: {:detail => I18n.t('logs.destroy_group', group_name: self.name)}
  end
end

app/controllers/user_groups_controller.rb
# This controller is used to manager user_group
# History: June 06, 2013
# By NamTV

class UserGroupsController < ApplicationController
  before_filter :authenticate_user!
  SORT_GROUP_MAP = {
    1 => "name"
  }
  SORT_USER_MAP = {
    1 => "full_name",
    2 => "username"
  }

  ##
  #Get user_group list except an user_group of Administrator
  #Parameters::
  # * (Integer) *iDisplayLength*: number of row per page
  # * (Integer) *iDisplayStart*:  starting number
  # * (Integer) *iSortCol_0*: locate of sort column
  # * (String)  *sSearch*: Search string
  #Return::
  # * (json) Matched user list with paging and number all rows are finded
  #*Author*:: PhuND
  def index
    if request.xhr?
      organization_id = params["organization_id"]
      per_page = params[:iDisplayLength] || Settings.per_page
      page = params[:iDisplayStart] ? ((params[:iDisplayStart].to_i/per_page.to_i) + 1) : 1
      params[:iSortCol_0] = 1 if params[:iSortCol_0].blank?
      sort_field = SORT_GROUP_MAP[params[:iSortCol_0].to_i]
      @user_groups = UserGroup.get_all_user_groups(page, per_page, params[:sSearch], sort_field + " " + params[:sSortDir_0],organization_id)
      render :json => @user_groups
      return
    end
  end

  ##
  #New an user group
  #Parameters::
  #Return::
  # * (Array) Permission load form initialize
  # *  Model: new instance of User Group
  #*Author*:: PhuND
  def new
    @user_group = UserGroup.new
    @permissions = {}
    @group_permissions = Permission.get_group_permissions
    @group_permissions.each do |g|
      @permissions[g.group_permission_name] = Permission.get_permission_in_group_permission(g.group_permission_name)
    end
  end

  ##
  #Creat user group
  #Parameters::
  # * (object) *user_group*: current user_group object
  # * (Array) *permissions*: permission list that user group have
  #Return::
  # * (object) an new instance user_group
  #*Author*:: PhuND
  def create
    @user_group = UserGroup.new(params["user_group"])
    permission_ids = params["permissions"]
    org_id = params[:organization_id]
    @user_group.permission_ids = permission_ids
    @user_group.organization_id = org_id

    if @user_group.save
      redirect_to organization_user_groups_path
    else
      flash[:error] = t('user_group.exist')
      @permissions = Permission.get_hash_group_permission
      render :new
    end

  end

  ##
  #Get user group with specify ID
  #Parameters::
  # * (Integer) *id*: current user group id
  #Return::
  # * (User Group) Matched user with id
  #*Author*:: PhuND
  def edit
    @user_group = UserGroup.find_by_id(params[:id])
    # @permissions = Permission.get_hash_group_permission
    @selected_permisions = @user_group.get_hash_selected_permissions
    p "<<<<<<<<<<<<<<<<<<<<<<"
    p @selected_permisions
    if request.xhr?
      organization_id = params["organization_id"]
      per_page = params[:iDisplayLength] ||  Settings.per_page
      page = params[:iDisplayStart] ? ((params[:iDisplayStart].to_i/per_page.to_i) + 1) : 1
      params[:iSortCol_0] = 1 if params[:iSortCol_0].blank?
      sort_field = SORT_USER_MAP[params[:iSortCol_0].to_i]

      @users = UserGroup.get_all_users_in_group(page, per_page, params[:sSearch], sort_field + " " + params[:sSortDir_0],organization_id,params[:id])
      render :json => @users, :view =>:edit_temp
      return
    end
    render :edit_temp
  end

  def get_available_user
    if request.xhr?
      organization_id = params["organization_id"]
      per_page = params[:iDisplayLength] ||  Settings.per_page
      page = params[:iDisplayStart] ? ((params[:iDisplayStart].to_i/per_page.to_i) + 1) : 1
      params[:iSortCol_0] = 1 if params[:iSortCol_0].blank?
      sort_field = SORT_USER_MAP[params[:iSortCol_0].to_i]

      @all_users = UserGroup.get_all_users_not_in_group(page, per_page, params[:sSearch], sort_field + " " + params[:sSortDir_0],organization_id, params[:user_group_id])

      render :json => @all_users, :view =>:edit_temp
      return
    end
  end

  def add_user_to_group
    @user_group = UserGroup.find_by_id(params[:user_group_id])
    if params[:ids]
      users = User.find(params[:ids])
      case params[:process]
        when "addItem", "addAllItems"
          @user_group.users << users
          @user_group.save
        when "removeItem", "removeAllItems"
          @user_group.users.delete(users)
          @user_group.save
      end
    end
    render :json => @user_group.users,:view =>:edit_temp
  end

  def update_permissions
    @user_group = UserGroup.find_by_id(params[:user_group_id])
    if(params[:process] == "all")
      @selected_permisions = @user_group.get_hash_selected_permissions
      render :json => {permissions: @selected_permisions, message: "Success"},:view =>:edit_temp
      return
    end
    if params[:ids]
      permissions = Permission.find(params[:ids])
      case params[:process]
        when "add"
          @user_group.permissions << permissions
          @user_group.save
        when "remove"
          @user_group.permissions.delete(permissions)
          @user_group.save
      end
    end
     @selected_permisions = @user_group.get_hash_selected_permissions
    render :json => @selected_permisions,:view =>:edit_temp
  end

  #
  #Handle detroy an user_group
  #Parameters::
  # * (integer) *id*: current user_group id to destroy
  #Return::
  # * (json) status: ok=>done
  #*Author*:: PhuND
  #
  def destroy
    @user_group = UserGroup.find_by_id(params[:id])
    @user_group.destroy
    render :json=>{:status =>t('users.destroy.success')}
  end

  #Update user group with specify ID
  #Parameters::
  # * (Integer) *id*: current user group id
  # * (Array) *permissions*: permissions that user group have
  #Return::
  # * (User) Matched user group with id
  #*Author*:: PhuND
  def update
    @user_group = UserGroup.find_by_id(params[:id])
    permission_ids = params["permissions"] || []
    permission_ids.map! {|p| p.to_i}
    current_permission_ids = @user_group.permission_ids
    group_name =  params["user_group"]["name"]

    existed_group = UserGroup.where(:name =>group_name)
    if existed_group.empty? || existed_group.first.id == params[:id].to_i
      if @user_group.update_attributes(params["user_group"])

        # The update action make log saved or not
        is_logged = !@user_group.previous_changes.blank?
        if current_permission_ids != permission_ids
          @user_group.permission_ids = permission_ids

          # Create log if not logged before
          @user_group.create_activity :update, owner: current_user, params: {:detail => I18n.t('logs.update_group', group_name: @user_group.name)} if !is_logged
        end
        redirect_to organization_user_groups_path(params[:organization_id])
      end
    else
      flash[:error] = t('user_group.exist')
      redirect_to edit_organization_user_group_path(params[:organization_id],@user_group)
    end
  end

end

app/views/user_groups/_list_user.html.haml
%center
  %table#dialog_table
    %tr
      %td
        %b
          = t('user_group.dialog.table_1')
        .grid_dual
          %table#user1_tab_table.display
            %div
      %td
        %div
          %center
            %input#btnAdd{:type => "button", :value => t('user_group.dialog.add_items'), :onclick => "addSelectedItems();"}
            %br
            %input#btnAddAll{:type => "button", :value => t('user_group.dialog.add_all_items'), :onclick => "addAllItems();"}
            %br
            %input#btnRemove{:type => "button", :value => t('user_group.dialog.remove_items')  , :onclick => "removeSelectedItems();"}
            %br
            %input#btnRemoveAll{:type => "button", :value => t('user_group.dialog.remove_all_items'), :onclick => "removeAllItems();"}
      %td
        %b
          = t('user_group.dialog.table_2')
        .grid_dual
          %table#user2_tab_table.display
            %div

= javascript_include_tag "dual_table"

app/views/user_groups/_permissions.html.haml
- p "=============="
- p permissions
- if permissions.blank?
  %label
    %i
      = t('permission.no_exist')
-else
  .group
    - permissions.each do |key, value|
      %label
        = key
        %label
          - value.each do |p|
            %input{:type=>"checkbox",:name=>"permissions[]",:value=>"#{p.id}",:checked => selected_permission_ids.include?(p.id) ? "true":nil}
              = p.name
              %br
/ - if permissions.blank?
/   %label
/     %i
/       = t('permission.no_exist')
/ -else
/   .group
/     - permissions.each do |key, value|
/       - flag = false
/       - value.each do |p|
/         - if selected_permission_ids.include?(p.id)
/           - if !flag
/             %label
/               = key
/             - flag = true
/           %label
/             %input{:type=>"checkbox",:name=>"permissions[]",:value=>"#{p.id}"}
/               = p.name
/               %br

app/views/user_groups/_selected_permissions.html.haml
- permissions = @selected_permisions
- if permissions.blank?
  %label
    %i
      = t('permission.no_exist')
-else
  .group{:style =>"height: 500px;"}
    - permissions.each do |key, value|
      %label
        = key
        %label
          - value.each do |p|
            %input{:type=>"checkbox",:name=>"permissions[]",:class => "permissions",:value=>"#{p.id}"}
              = p.name
              %br


:javascript
  var obj = JSON.parse();
  function getCheckBoxes(checkBoxClass){
    var selected_ids = new Array;
    var checkBoxes = $('.' + checkBoxClass);
    $.each(checkBoxes, function() {
      if ($(this).is(':checked')){
        selected_ids.push($(this).val());
      }
    });
    return selected_ids;
  }
  function loadPermission(){
    $.ajax({
        url:updatePermissionsToGroup,
        data: {
          process: "all"
        },
        success:function(result){
          $("#div1").html(result);
        }
      });
  }

  function removePermissions() {
    var permissions = getCheckBoxes("permissions");
    //if(permissions.length > 0){
      $.ajax({
        url:updatePermissionsToGroup,
        data: {
          ids: permissions,
          process: "remove"
        },
        success:function(result){
          $("#div1").html(result);
        }
      });
    //}

   loadPermission();

    $('#tabs').tabs({
    load: function( event, ui ) {
        $("#tabs").tabs({active : 1})
      }
    });
  }

app/views/user_groups/edit.html.haml
.content
  %h2= t('user_group.edit')
  - unless flash[:error].nil?
    %div{:style=>'color: red'}
      = flash[:error]
    %br
  .new_form
    = form_for(@user_group,:url => organization_user_group_path,:method=>"PUT", :html => {:id=>"edit_user_group"}) do |f|
      .text_input
        %div
          = t('user_group.name')
          %span{:class=>"require"} (*)
        =f.text_field :name
      .text_input
        %div
          = t('user_group.description')
          %span{:class=>"require"} (*)
        =f.text_area :description, :size => "24x6"
      = t('permission.title')
      = render "permissions", :permissions => @permissions,:selected_permission_ids => @user_group.permission_ids
      %br
      %div
        = t('user_group.status')
        %label
          = f.radio_button :is_active, true
          = t('user_group.status_enable')
        %label
          = f.radio_button :is_active, false
          = t('user_group.status_disable')
      %br
      .space
      %div
        = f.submit t('button.save'),:class=>"btn_submit"
        = f.button t('button.cancel'),:class=>"btn_submit",:onclick =>"window.location = g_userGroupsPath;return false;"

= javascript_include_tag "user_group"
:javascript
  //Variable Declaration
  var id = "#{params[:id]}";
  //Default focus
  $("#user_group_name").focus();

app/views/user_groups/edit_temp.html.haml
.content
  #tabs
    %ul
      %li
        = link_to "General Information", "#tabs-1"
      %li
        = link_to "List of Users", "#tabs-2"
      %li
        = link_to "Function", "#tabs-3"
    #tabs-1
      %h2= t('user_group.edit')
      - unless flash[:error].nil?
        %div{:style=>'color: red'}
          = flash[:error]
        %br
      .new_form
        = form_for(@user_group,:url => organization_user_group_path,:method=>"PUT", :html => {:id=>"edit_user_group"}) do |f|
          .text_input
            %div
              = t('user_group.name')
              %span{:class=>"require"} (*)
            =f.text_field :name
          .text_input
            %div
              = t('user_group.description')
              %span{:class=>"require"} (*)
            =f.text_area :description, :size => "24x6"
          = t('permission.title')
          = render "permissions", :permissions => @permissions,:selected_permission_ids => @user_group.permission_ids
          / = render "selected_permissions", :permissions => @selected_permisions
          %br
          %div
            = t('user_group.status')
            %label
              = f.radio_button :is_active, true
              = t('user_group.status_enable')
            %label
              = f.radio_button :is_active, false
              = t('user_group.status_disable')
          %br
          .space
          %div
            = f.submit t('button.save'),:class=>"btn_submit"
            = f.button t('button.cancel'),:class=>"btn_submit",:onclick =>"window.location = g_userGroupsPath;return false;"
    #tabs-2
      .right_search_panel
        %input.btn_add_user#btn_dialog{:type=>"button",:value=>t('button.add_user')}
      .grid{:style=>"clear:both"}
        %table#user_tab_table.display
          %div
      #dialog{:title => t('user_group.dialog.title'), :style => "display:none"}
        = render "list_user"
    #tabs-3
      = t('permission.title')
      .right_search_panel
        %input.btn_add_user#btn_dialog{:type=>"button",:value=>t('button.add_user')}
        %input#btn_remove_permission{:type => "button", :value => "remove", :onclick => "removePermissions();"}
      %label
        #draw_data

= javascript_include_tag "user_group"
= javascript_include_tag "edit_user_group"


:javascript
  var oTable1;
  var oTable2;
  var flagRenderTable = 0;
  $("#btn_dialog").click(function (e)
    {
      $( "#dialog" ).dialog({
        height: 800,
        width : 1000,
        modal: true
      });
      if(flagRenderTable == 0){
        oTable1 = renderPopupTable("#user1_tab_table");
        oTable2 = renderPopupTable("#user2_tab_table");
        flagRenderTable = 1;
      }
    });
  //Variable Declaration
  var id = "#{params[:id]}";
  var updateUsersToGroupPath = "#{organization_user_group_add_user_to_group_path(params[:organization_id],params[:id])}";
  var getAllUsersPath = "#{organization_user_group_get_available_user_path(params[:organization_id],params[:id])}";
  var editUserGroupPath = "#{edit_organization_user_group_path(params[:organization_id],params[:id])}";
  var updatePermissionsToGroup = "#{organization_user_group_update_permissions_path(params[:organization_id],params[:id])}";
  //Default focus
  $("#user_group_name").focus();

app/views/user_groups/index.html.haml
#user_grid
  .grid_toolbar
    .grid_title
      = t('user_group.list_name')
    .right_search_panel
      %input.btn_add_user{:type=>"button",:value=>t('button.add_user_group'),:onclick=>"window.location = g_newUserGroupPath"}
  .grid{:style=>"clear:both"}
    %table#user_group_table.display
      %div

= javascript_include_tag "user_group"
:javascript
  // Variable Declaration
  var g_token = '#{form_authenticity_token}';

app/views/user_groups/new.html.haml
.content
  %h2= t('user_group.new')

  - unless flash[:error].nil?
    %div{:style=>'color: red'}
      = flash[:error]
    %br
  .new_form
    = form_for(@user_group,:url => organization_user_groups_path) do |f|
      %div
        .text_input
          %div
            = t('user_group.name')
            %span.require (*)
          =f.text_field :name,:class=>"required"
        .text_input
          %div
            = t("user_group.description")
            %span.require (*)
          =f.text_area :description,:class=>"required", :size => "24x6"
      %h2= t('permission.title')
      = render "permissions", :permissions => @permissions,:selected_permission_ids => @user_group.permissions
      %br
      .space
      = f.submit t('button.save'),:class=>"btn_submit"
      %input{:type=>"button", :class=>"btn_submit", :onclick =>"window.location = g_userGroupsPath",:value=>t('button.cancel')}

= javascript_include_tag "user_group"
:javascript
  //set default focus
  $("#user_group_name").focus();

app/views/user_groups/new_temp.html.haml
.content
  #tabs
    %ul
      %li
        = link_to "General Information", "#tabs-1"
      %li
        = link_to "Function", "#tabs-2"
      %li
        = link_to "List of Users", "#tabs-3"
    #tabs-1
      %h2= t('user_group.new')
      - unless flash[:error].nil?
        %div{:style=>'color: red'}
          = flash[:error]
        %br
      .new_form
        = form_for(@user_group,:url => organization_user_groups_path) do |f|
          %div
            .text_input
              %div
                = t('user_group.name')
                %span.require (*)
              =f.text_field :name,:class=>"required"
            .text_input
              %div
                = t("user_group.description")
                %span.require (*)
              =f.text_area :description,:class=>"required", :size => "24x6"
          %h2= t('permission.title')
          = render "permissions", :permissions => @permissions,:selected_permission_ids => @user_group.permissions
          %br
          .space
          = f.submit t('button.save'),:class=>"btn_submit"
          %input{:type=>"button", :class=>"btn_submit", :onclick =>"window.location = g_userGroupsPath",:value=>t('button.cancel')}
    #tabs-2
      fsdfs
    #tabs-3
      fdadasd

= javascript_include_tag "user_group"
= javascript_include_tag "edit_user_group"


:javascript
  var oTable1;
  var oTable2;
  var flagRenderTable = 0;
  $("#btn_dialog").click(function (e)
    {
      $( "#dialog" ).dialog({
        height: 800,
        width : 1000,
        modal: true
      });
      if(flagRenderTable == 0){
        oTable1 = renderPopupTable("#user1_tab_table");
        oTable2 = renderPopupTable("#user2_tab_table");
        flagRenderTable = 1;
      }
    });
  //Variable Declaration
  var id = "#{params[:id]}";
  //Default focus
  $("#user_group_name").focus();