config/routes.rb
HelloWorld::Application.routes.draw do

  devise_for :users, :path => "auth",:controllers =>{passwords: "passwords", registrations: 'registrations'}
  resources :settings do
    post "normal_upload", :on => :collection
  end

  resources :banners do
  end
  
  resources :advertisings do
  end
  
  resources :categories
  resources :orders
  resources :organizations do
    resources :users

    resources :user_groups do
      get "get_available_user"
      get "add_user_to_group"
      get "update_permissions"
    end

    resources :activities
  end
  resources :calendars do
    get "contact",:on => :collection
    post "send_contact",:on => :collection
    get "product_contact"
    get "send_product_contact",:on =>:collection
    get "admin",:on =>:collection
  end
  root :to => 'home#index'
  resources :home do
    get "introduction",:on => :collection
    get "pricing_page",:on => :collection
  end

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  attr_accessible  :image

  has_attached_file :image,
    # :path => ":rails_root/public/images/:id/:filename",
    # :url  => "/images/:id/:filename",

    :styles => {:large =>"800x360", :medium => "300x300>", :thumb => "100x100#",
    :default_url => '/assets/img_lich/lich_bloc.jpg' }
  #do_not_validate_attachment_file_type :image
  validates_attachment_content_type :image, :content_type => /image/
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_filter :authenticate_user!
  layout "admin"
  def edit
    @banner = Banner.first
    @banner = Banner.new if @banner.blank?
    puts @banner.inspect
  end
  
  def update
    @banner = Banner.first
    @banner = @banner.update_attributes(params[:banner])
    redirect_to edit_banner_path({:id => 1,:succes =>"true"})
  end

  def create
    @banner = Banner.new(params[:banner])
    if @banner.save
      redirect_to edit_banner_path({:id => 1,:success =>"true"})
    else
      render :edit
    end
  end
end

app/views/banners/_form.html.haml
- if params[:success]
  %div{:style =>"color:green"}
    Banner đã được cập nhật thành công.
- url = @banner.new_record? ? banners_path : banner_path
= form_for @banner, :url => url, :html => { :multipart => true } do |form|
  - if @banner.errors.any?
    .alert.alert-error
      %div.head-error Có lỗi xảy ra. Vui lòng sửa các lỗi sau:
      %div.content-error
        %ul{:style => "list-style:none; padding:10px 10px 10px 10px;"}
          - for message in @banner.errors.full_messages
            %li.li-error= message
  = form.file_field :image
  %br
  =form.submit "Lưu",:class=>"art-button"

app/views/banners/edit.html.haml
%h1{:style =>"color: black"}
  Sửa banner
%hr{:size => 1,:style =>"color: lightgray;margin: 1px 0px"}
%div
  =render :partial => "form"