config/routes.rb
HelloWorld::Application.routes.draw do

  devise_for :users, :path => "auth",:controllers =>{passwords: "passwords", registrations: 'registrations'}
  resources :settings do
    post "normal_upload", :on => :collection
  end

  resources :banners do
  end
  
  resources :advertisings do
  end
  
  resources :categories
  resources :orders
  resources :organizations do
    resources :users

    resources :user_groups do
      get "get_available_user"
      get "add_user_to_group"
      get "update_permissions"
    end

    resources :activities
  end
  resources :calendars do
    get "contact",:on => :collection
    post "send_contact",:on => :collection
    get "product_contact"
    get "send_product_contact",:on =>:collection
    get "admin",:on =>:collection
  end
  root :to => 'home#index'
  resources :home do
    get "introduction",:on => :collection
    get "pricing_page",:on => :collection
  end

end

app/views/shared/_detail_slider.html.haml
=javascript_include_tag "slider/slider_inline"
= stylesheet_link_tag "slider_inline"
#slider1_container{:style => "position: relative; top: 0px; left: 0px; height: 456px; background: #191919; overflow: hidden;"}
  / Loading Screen
  %div{:style => "position: absolute; top: 0px; left: 0px;", :u => "loading"}
    %div{:style => "filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;             background-color: #000000; top: 0px; left: 0px;width: 100%;height:100%;"}
    %div{:style => "position: absolute; display: block; background: url(assets/slider/loading.gif) no-repeat center center;top: 0px; left: 0px;width: 100%;height:100%;"}
  / Slides Container
  %div.slide_custom{:style => "cursor: move; position: absolute; left: 0px; top: 0px; height: 356px; overflow: hidden;", :u => "slides"}
    -if calendar.photos.blank?
      %div
        %img{:src => "/assets/slider/alila/lich_1.jpg", :u => "image"}/
        %img{:src => "/assets/slider/alila/lich_1.jpg", :u => "thumb"}/
      %div
        %img{:src => "/assets/slider/alila/lich_2.jpg", :u => "image"}/
        %img{:src => "/assets/slider/alila/lich_2.jpg", :u => "thumb"}/
      %div
        %img{:src => "/assets/slider/alila/lich_3.jpg", :u => "image"}/
        %img{:src => "/assets/slider/alila/lich_3.jpg", :u => "thumb"}/
      %div
        %img{:src => "/assets/slider/alila/lich_4.jpg", :u => "image"}/
        %img{:src => "/assets/slider/alila/lich_4.jpg", :u => "thumb"}/
      %div
        %img{:src => "/assets/slider/alila/lich_5.jpg", :u => "image"}/
        %img{:src => "/assets/slider/alila/lich_5.jpg", :u => "thumb"}/
      %div
        %img{:src => "/assets/slider/alila/lich_6.jpg", :u => "image"}/
        %img{:src => "/assets/slider/alila/lich_6.jpg", :u => "thumb"}/
      %div
        %img{:src => "/assets/slider/alila/lich_7.jpg", :u => "image"}/
        %img{:src => "/assets/slider/alila/lich_7.jpg", :u => "thumb"}/
    -else
      -calendar.photos.each do |i|
        %div
          %img{:src => "#{i.image.url(:original)}", :u => "image"}/
          %img{:src => "#{i.image.url(:thumb)}",:width => "72px", :height =>"72px", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/08.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-08.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/09.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-09.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/10.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-10.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/11.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-11.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/12.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-12.jpg", :u => "thumb"}/
  / Arrow Navigator Skin Begin
  / Arrow Left
  %span.jssora05l{:style => "width: 40px; height: 40px; top: 158px; left: 8px;", :u => "arrowleft"}
  / Arrow Right
  %span.jssora05r{:style => "width: 40px; height: 40px; top: 158px; right: 8px", :u => "arrowright"}
  / Arrow Navigator Skin End
  / Thumbnail Navigator Skin Begin
  .jssort01{:style => "position: absolute; height: 100px; left:0px; bottom: 0px;", :u => "thumbnavigator"}
    / Thumbnail Item Skin Begin
    %div{:style => "cursor: move;", :u => "slides"}
      .p{:style => "position: absolute; width: 72px; height: 72px; top: 0; left: 0;", :u => "prototype"}
        .w
          %thumbnailtemplate{:style => " width: 100%; height: 100%; border: none;position:absolute; top: 0; left: 0;"}
        .c
    / Thumbnail Item Skin End
  %a{:href => "http://www.jssor.com", :style => "display: none"} javascript

app/views/shared/_detail_slider2.html.haml
=#javascript_include_tag ""
= stylesheet_link_tag "flexslider"
= stylesheet_link_tag "demo"
%div
  .flexslider{:id =>"slider"}
    %ul.slides
      -calendar.photos.each do |i|
        %li
          %img{:src => "#{i.image.url(:original)}"}/
  .flexslider{:id =>"carousel"}
    %ul.slides
      -calendar.photos.each do |i|
        %li
          %img{:src => "#{i.image.url(:original)}"}/
:javascript
  $(function(){
      SyntaxHighlighter.all();
    });
    $(window).load(function(){

      $('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 210,
        itemMargin: 5,
        asNavFor: '#slider'
      });

      $('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: true,
        slideshow: true,
        sync: "#carousel",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });

    });

app/views/shared/_home_slider.html.haml
=javascript_include_tag "slider/slider_inline"
= stylesheet_link_tag "slider_inline"
#slider1_container{:style => "position: relative; top: 0px; left: 0px; height: 456px; background: #191919; overflow: hidden;"}
  / Loading Screen
  %div{:style => "position: absolute; top: 0px; left: 0px;", :u => "loading"}
    %div{:style => "filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;             background-color: #000000; top: 0px; left: 0px;width: 100%;height:100%;"}
    %div{:style => "position: absolute; display: block; background: url(assets/slider/loading.gif) no-repeat center center;top: 0px; left: 0px;width: 100%;height:100%;"}
  / Slides Container
  %div.slide_custom{:style => "cursor: move; position: absolute; left: 0px; top: 0px; height: 356px; overflow: hidden;", :u => "slides"}
    %div
      %img{:src => "assets/slider/alila/lich_1.jpg", :u => "image"}/
      %img{:src => "assets/slider/alila/lich_1.jpg", :u => "thumb"}/
    %div
      %img{:src => "assets/slider/alila/lich_2.jpg", :u => "image"}/
      %img{:src => "assets/slider/alila/lich_2.jpg", :u => "thumb"}/
    %div
      %img{:src => "assets/slider/alila/lich_3.jpg", :u => "image"}/
      %img{:src => "assets/slider/alila/lich_3.jpg", :u => "thumb"}/
    %div
      %img{:src => "assets/slider/alila/lich_4.jpg", :u => "image"}/
      %img{:src => "assets/slider/alila/lich_4.jpg", :u => "thumb"}/
    %div
      %img{:src => "assets/slider/alila/lich_5.jpg", :u => "image"}/
      %img{:src => "assets/slider/alila/lich_5.jpg", :u => "thumb"}/
    %div
      %img{:src => "assets/slider/alila/lich_6.jpg", :u => "image"}/
      %img{:src => "assets/slider/alila/lich_6.jpg", :u => "thumb"}/
    %div
      %img{:src => "assets/slider/alila/lich_7.jpg", :u => "image"}/
      %img{:src => "assets/slider/alila/lich_7.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/08.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-08.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/09.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-09.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/10.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-10.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/11.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-11.jpg", :u => "thumb"}/
    / %div
    /   %img{:src => "assets/slider/alila/12.jpg", :u => "image"}/
    /   %img{:src => "assets/slider/alila/thumb-12.jpg", :u => "thumb"}/
  / Arrow Navigator Skin Begin
  / Arrow Left
  %span.jssora05l{:style => "width: 40px; height: 40px; top: 158px; left: 8px;", :u => "arrowleft"}
  / Arrow Right
  %span.jssora05r{:style => "width: 40px; height: 40px; top: 158px; right: 8px", :u => "arrowright"}
  / Arrow Navigator Skin End
  / Thumbnail Navigator Skin Begin
  .jssort01{:style => "position: absolute; height: 100px; left:0px; bottom: 0px;", :u => "thumbnavigator"}
    / Thumbnail Item Skin Begin
    %div{:style => "cursor: move;", :u => "slides"}
      .p{:style => "position: absolute; width: 72px; height: 72px; top: 0; left: 0;", :u => "prototype"}
        .w
          %thumbnailtemplate{:style => " width: 100%; height: 100%; border: none;position:absolute; top: 0; left: 0;"}
        .c
    / Thumbnail Item Skin End
  %a{:href => "http://www.jssor.com", :style => "display: none"} javascript

app/views/shared/_intro.html.haml
/ %h1.color-black{:style=>"color:black"}
/   LỜI GIỚI THIỆU
/ %p.color-black
/   Vào những dịp cuối năm thì món quà mà hầu hết các doanh ghiệp thường biếu tặng khách hàng của mình chính là những bộ lịch Tết. Điều này vừa thể hiện nét đẹp văn hóa riêng của dân tộc vừa tạo cảm giác gần gũi, ý nghĩa, thắt chặt tình cảm giữa doanh nghiệp với khách hàng. Lịch Tết vừa là giải pháp quảng cáo tốt đồng thời tạo ấn tượng đẹp trong lòng khách hàng của mình.
/ %p.color-black
/   Với mong mõi cung cấp thật tốt cho thị trường Lịch 2015, công ty TNHH TÂN PHƯƠNG là đơn vị Chuyên THIẾT KẾ và IN ẤN LỊCH cho các Công ty, Cơ quan, Cơ sở kinh doanh, Cá nhân, Trường học, Bệnh viện, Siêu thị... . Công ty TNHH TÂN PHƯƠNG cam kết đưa ra giá cực tốt cho Quý khách hàng đồng hành với Chất lượng tuyệt đối. Chúng tôi chuyên nhận in lịch tết 2015, in lịch để bàn 2015, in lịch độc quyền 2015, in lịch 1 tờ, in Lịch 5 tờ, in Lịch 7 tờ, in Lịch 12 tờ, in Lịch Bloc, in Lịch treo tường, in Lịch lò xo giữa, in Lịch nẹp thiếc... 
/ %p.color-black
/   %div.content-image 
/     =image_tag "/assets/template/Lichban/lich-deban-phongthuy.jpg"
/   %div.note-image{:style=>"text-align:center; font-size:10px;"}
/     Hình 1: Lịch để bàn phong thủy 



/ %p.color-black
/   Đặc biệt công ty còn thiết kế In ấn các loại vật phẩm quảng cáo làm quà tặng. Đa dạng nhiều chủng loại vật phẩm độc đáo. Được In trên nhiều chất liệu khác nhau: in trên đá, in trên vải lụa, pha lê, gốm sứ... .
/ %p.color-black
/   %div.content-image-height
/     =image_tag "/assets/template/LichBiaGangLich/HN-16.jpg"
/   %div.note-image{:style=>"text-align:center; font-size:10px;"}
/     Hình 2: Lịch Bìa 
/ %p.color-black
/   %div.content-image-height
/     =image_tag "/assets/template/LichTuong/lich_tuong_02.jpg"
/   %div.note-image{:style=>"text-align:center; font-size:10px;"}
/     Hình 3: Lịch Tường

/ %p.color-black
/   Với phương châm “Chất lượng đi trước”, công ty TNHH TÂN PHƯƠNG luôn cố gắng làm hài lòng khách hàng bằng chất lượng tốt nhất và giá cả cạnh tranh, có lực lượng chăm sóc khách hàng hùng hậu, gọi đâu có đó. Năm mới 2015 sắp đến, tập thể công ty TNHH TÂN PHƯƠNG kính chúc Quý khách hàng nhiều may mắn, sức khỏe và bình an.
=intro.blank? ? "" : (raw intro.value)

app/views/shared/_menu.html.haml
%ul#jMenu
  - if current_user
    - org_id = (controller.controller_name == 'organizations' && !params[:id] && !params[:organization_id]) ? current_user.organization_id : (params[:organization_id] || params[:id] || current_user.organization_id)
    %li.border_right
      - if can? :index, User
        = link_to t('menu.user_management'), organization_users_path(org_id),:class=>"fNiv #{'link_active' if controller.controller_name =="users"}",:id=>"menu_user"
    %li.border_right
      - if can? :index, UserGroup
        = link_to t('menu.user_group_management'), organization_user_groups_path(org_id),:class=>"fNiv #{'link_active' if controller.controller_name =="user_groups"}",:id=>"menu_user_group"
    %li.border_right
      - if can? :index, Activity
        = link_to t('menu.log'), organization_activities_path(org_id),:class=>"fNiv #{'link_active' if controller.controller_name =="activities"}",:id=>"menu_log"

    %li.border_right
      - if can? :index, Organization
        = link_to t('menu.organization'), organizations_path,:class=>"fNiv #{'link_active' if controller.controller_name =="organizations"  && controller.action_name != "show"}",:id=>"menu_organization"
    %li.border_right
      - if can? :show, Organization
        = link_to t('menu.my_organization'), organization_path(current_user.organization_id),:class=>"fNiv #{'link_active' if controller.controller_name =="organizations" && controller.action_name == "show"}",:id=>"menu_my_organization"

app/views/shared/_widget.html.haml
.custom-widget.div-a2{:onclick =>"window.location='#{calendar_path(calendar.id)}'"}
  .widget-content
    .widget-image
      %img{:src=>"#{render_first_photo(calendar.photos)}"}
    .widget-text
      .elip-text{:style =>"font-weight:bold"}
        = calendar.name.truncate(40)
      / .elip-text.sm-text
      /   = calendar.description.blank? ? "&nbsp;".html_safe : calendar.description.truncate(40).to_s
      .elip-text.sm-text
        Kích thước:
        = calendar.size
      .elip-text.sm-text
        Loại Giấy: 
        = calendar.paper_type
      .more_info
        %a{:href => "#{calendar_path(calendar.id)}"} Chi tiết >>